In [1]:
import numpy as np

In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

### Mean Absolute Error

In [5]:
def mae(y_predicted,y_true):
    total_error=0
    for yp,yt in zip(y_predicted,y_true):
        total_error+=abs(yp-yt)
    print("Total error: ",total_error)
    mae=total_error/len(y_true)
    print("Mean Absolute Error: ",mae)
    
mae(y_predicted,y_true)

Total error:  2.5
Mean Absolute Error:  0.5


#### By using numpy

In [6]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [7]:
np.mean(np.abs(y_predicted-y_true))

0.5

### Log Loss or Binary Cross Entropy

In [10]:
np.log(0)

C:\Users\visha\AppData\Local\Temp/ipykernel_11492/2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [11]:
epsillon= 1e-15

In [12]:
np.log(epsillon)

-34.538776394910684

In [17]:
y_pred_new=[max(i,epsillon) for i in y_predicted]
y_pred_new

[1, 1, 1e-15, 1e-15, 1]

In [18]:
y_pred_new=[min(i,1-epsillon) for i in y_pred_new]
y_pred_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [19]:
y_pred_new=np.array(y_pred_new)
y_pred_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [20]:
np.log(y_pred_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [22]:
-np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

17.2696280766844

### Mean Square Error

In [23]:
def mse(y_predicted,y_true):
    total_error=0
    for yp,yt in zip(y_predicted,y_true):
        total_error+=(yp-yt)**2
    print("Total error: ",total_error)
    mae=total_error/len(y_true)
    print("Mean Squared Error: ",mae)
    
mse(y_predicted,y_true)

Total error:  1.83
Mean Squared Error:  0.366


In [24]:
np.mean((y_predicted-y_true)**2)

0.366