In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow import keras

In [13]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [14]:
one_hot("amazing restaurant",50)

[38, 31]

In [15]:
vocab_size=50
encoded_reviews= [one_hot(d,vocab_size) for d in reviews]
print(encoded_reviews)

[[41, 16], [38, 31], [37, 44], [22, 5, 13], [49, 15, 15], [25, 16], [15, 15, 28], [38, 48], [38, 44], [33, 13]]


In [16]:
max_length=4
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[41 16  0  0]
 [38 31  0  0]
 [37 44  0  0]
 [22  5 13  0]
 [49 15 15  0]
 [25 16  0  0]
 [15 15 28  0]
 [38 48  0  0]
 [38 44  0  0]
 [33 13  0  0]]


In [18]:
embeded_vec_size=5

In [22]:
model=keras.Sequential()
model.add(keras.layers.Embedding(vocab_size,embeded_vec_size,input_length=max_length,name="embedding"))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(1,activation='sigmoid'))

In [23]:
X=padded_reviews
y=sentiment

In [24]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              250       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 271
Trainable params: 271
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.fit(X,y,epochs=50,verbose=0)

In [26]:
loss,accuracy=model.evaluate(X,y)
accuracy 

1/1 [==============================] - 0s 215ms/step - loss: 0.6296 - accuracy: 0.9000


0.8999999761581421

In [27]:
weights=model.get_layer('embedding').get_weights()[0]

In [28]:
len(weights)

50

In [29]:
weights[41]

array([-0.02878996,  0.04782077, -0.06871587,  0.07735995, -0.08952743],
      dtype=float32)

In [30]:
weights[38]

array([ 0.06420266, -0.04507448,  0.08218966, -0.07431084,  0.04784197],
      dtype=float32)